# Joins
INIT = 0
EXACT_TOKENS_IN_FOR_SPT_OUT = 1
TOKEN_IN_FOR_EXACT_SPT_OUT = 2
ALL_TOKENS_IN_FOR_EXACT_SPT_OUT = 3

#Exits
EXACT_SPT_IN_FOR_ONE_TOKEN_OUT = 4
EXACT_SPT_IN_FOR_TOKENS_OUT = 5
SPT_IN_FOR_EXACT_TOKENS_OUT = 6

GIVEN_IN = 7
GIVEN_OUT = 8

# Storage
TOTAL_TOKENS = 10
ATH_RATE_PRODUCT = 11
POST_JOIN_EXIT_INVARIANT = 12
SWAP_FEE_PERCENTAGE = 13

# Math
MUL_DOWN = 20
MUL_UP = 21
DIV_DOWN = 22
DIV_UP = 23
POW_DOWN = 24
POW_UP = 25